[project]
name = "tsqlexec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.3",
    "pyodbc>=5.3.0",
]

[project.scripts]
tsqlexec = "tsqlexec.main:main"

[tool.uv]
package = true
